---
repos:
  - repo: https://github.com/0x08/google-style-precommit-hook
    rev: 503fa7c491becee130be17a10b03b275ce6f2330
    hooks:
      - id: google-style-java
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.0
    hooks:
      - id: prettier
  - repo: "https://github.com/adrienverge/yamllint"
    rev: v1.27.1
    hooks:
      - id: "yamllint"
        args: [--strict]
